### PR TITLE
fixed a few things =)

### PR DESCRIPTION
**Pull request by HoloPanio**

### CODE REVIEW

**Review by willdoescode — CHANGES_REQUESTED** [review]
re-write in php

**Review by willdoescode — CHANGES_REQUESTED** [review]
re-write in c

**Review by willdoescode — CHANGES_REQUESTED** [review]
re-write in brainfuck

**Review by willdoescode — CHANGES_REQUESTED** [review]
actual I want rust now pls

**Review by willdoescode — CHANGES_REQUESTED** [review]
void is not a type in rust

**Comment by willdoescode** [comment]
fixed in #1

**Comment by HoloPanio** [comment]
NO OPEN THIS BACK UP NOW

**Comment by willdoescode** [comment]
### idk

**Comment by HoloPanio** [comment]
common man I conceded with all of your requests

**Comment by willdoescode** [comment]
too many concedes

**Comment by HoloPanio** [comment]
*commits unalive*

**Comment by willdoescode** [comment]
- [ ] Eat cheese
- [ ] Be cool

**Comment by s3ansh33p** [comment]
rewrite in machine code - binary - or if that is too hard, try assembly

**Pull request closed without merging**
